#!/bin/bash

rm -rf ./build
mkdir build
cd ./build

module purge
module load cmake
module load gcc
#module load boost/1.50.0-gcc45
module load boost/1.55.0-gcc45
module load qt
module list

cmake -DUSE_QT4=ON ../
make langmuir
